language: node_js
node_js:
  - "8"
  - "10"
  - "12"
install:
  - npm i
  - npm i codecov
before_script:
  - npm run bootstrap
  - npm run build
script:
  - cd packages/serverless-invoke
  - npm run cov
after_script:
  - codecov
